##########
# GITHUB #
##########

# DOC
# https://github.com/actions/starter-workflows/

name: Design Pattern

on:
  push:
    branches: [ master ]

###
# Jobs
###
jobs:

  #########
  # TESTS #
  #########
  tests:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    # Php, composer, ext, xdebug
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "7.3"

    - name: Run tests
      run: php ./tests.php
